/**
 * Boating Decide starters — domain-local only.
 * Must not be merged into FIELD_SCENARIOS (fishing goldens stay fishing).
 */
import type { FieldScenario } from "@/data/scenarios";

export const BOATING_SCENARIOS: FieldScenario[] = [
  {
    id: "dock-cleat-surge",
    title: "Dock line · horn cleat · surge",
    blurb:
      "Make fast to a horn cleat so you can still cast off under load. A jammed lock is the hazard.",
    tag: "Dock · release",
    connectionLine: "Rope → cleat",
    likelyPick: "Cleat hitch when the first turn is on the far horn",
    autoRun: true,
    input: {
      connection: "rope-to-cleat",
      mainMaterial: "polyester",
      retieFrequency: "frequent",
      proficiency: "beginner",
    },
  },
  {
    id: "piling-overnight",
    title: "Piling overnight · cyclic tide",
    blurb:
      "Make fast to a piling you will leave. A clove hitch walks. The turn must take the load.",
    tag: "Mooring · tide",
    connectionLine: "Rope → bollard / piling",
    likelyPick: "Round turn and two half hitches over a clove",
    autoRun: true,
    input: {
      connection: "rope-to-bollard",
      mainMaterial: "nylon",
      retieFrequency: "rare",
      proficiency: "beginner",
    },
  },
  {
    id: "anchor-ring-soak",
    title: "Anchor ring · standing soak",
    blurb: "Rope to a ring that will stay wet. A hitch that works loose after a soak is the fail.",
    tag: "Anchorage",
    connectionLine: "Rope → ring",
    likelyPick: "Anchor bend; seize a standing job",
    autoRun: true,
    input: {
      connection: "rope-to-ring",
      mainMaterial: "nylon",
      retieFrequency: "rare",
      proficiency: "intermediate",
    },
  },
  {
    id: "standing-eye",
    title: "Standing eye in the end",
    blurb:
      "A fixed eye you will drop or clip. Collar must stay seated. An open bowline capsizes; a figure-eight jams after a snatch.",
    tag: "Loops · standing eye",
    connectionLine: "Fixed eye in the end",
    likelyPick: "Bowline when you must untie; figure-eight when the eye must stay inspectable",
    autoRun: true,
    input: {
      connection: "fixed-eye",
      mainMaterial: "polyester",
      needsUntie: true,
      retieFrequency: "occasional",
      proficiency: "beginner",
    },
  },
  {
    id: "eye-over-post",
    title: "Finished eye dropped over a post",
    blurb: "A loop you already have, dropped over a piling. Both legs must share the load.",
    tag: "Loops",
    connectionLine: "Loop over a post",
    likelyPick: "Cow hitch when both legs load; bowline if you still need to tie the eye",
    autoRun: true,
    input: {
      connection: "loop-over-post",
      mainMaterial: "polyester",
      retieFrequency: "occasional",
      proficiency: "beginner",
    },
  },
  {
    id: "join-two-docklines",
    title: "Join two dock lines",
    blurb: "Similar-diameter ropes. A sheet bend is fast; a Zeppelin still unties after load.",
    tag: "Join",
    connectionLine: "Rope → rope",
    likelyPick: "Zeppelin when you must untie; sheet bend when speed wins",
    autoRun: true,
    input: {
      connection: "rope-to-rope",
      mainMaterial: "polyester",
      secondaryMaterial: "polyester",
      diameterRelation: "similar",
      retieFrequency: "occasional",
      proficiency: "intermediate",
    },
  },
  {
    id: "unequal-heaving",
    title: "Heaving line onto a hawser",
    blurb: "Thinner line to a thicker one. Bight in the thick rope. One turn is not enough.",
    tag: "Mismatch",
    connectionLine: "Unequal join",
    likelyPick: "Double sheet bend",
    autoRun: true,
    input: {
      connection: "unequal-rope-join",
      mainMaterial: "polypropylene",
      secondaryMaterial: "polyester",
      diameterRelation: "main-much-thinner",
      proficiency: "beginner",
    },
  },
  {
    id: "snubber-chain",
    title: "Snubber onto chain",
    blurb:
      "Transfer load off the windlass. A rolling hitch is the first try; an icicle if it walks.",
    tag: "Anchorage · snubber",
    connectionLine: "Load transfer",
    likelyPick: "Rolling hitch first; icicle on a slick standing part",
    autoRun: true,
    input: {
      connection: "load-transfer",
      mainMaterial: "nylon",
      retieFrequency: "occasional",
      proficiency: "intermediate",
    },
  },
  {
    id: "midline-chafe",
    title: "Mid-line loop to isolate chafe",
    blurb: "A damaged section in the middle of a working line. An end-loop is the wrong job.",
    tag: "Working · mid-line",
    connectionLine: "Mid-line loop",
    likelyPick: "Alpine butterfly",
    autoRun: true,
    input: {
      connection: "mid-line-loop",
      mainMaterial: "polyester",
      retieFrequency: "rare",
      proficiency: "intermediate",
    },
  },
  {
    id: "taut-guy",
    title: "Guy line that must still adjust",
    blurb:
      "Tension a guy or awning you will still slide. A lock-and-leave purchase is the wrong job.",
    tag: "Working · tension",
    connectionLine: "Tension / lash",
    likelyPick: "Midshipman's hitch — the extra inside tuck is the hold",
    autoRun: true,
    input: {
      connection: "tension-line",
      mainMaterial: "polyester",
      retieFrequency: "frequent",
      proficiency: "intermediate",
    },
  },
  {
    id: "reef-a-sail",
    title: "Reef or furl — bind, do not join",
    blurb: "Two ends of the same line around a sail. A reef knot used as a bend will slip.",
    tag: "Bind · reefing",
    connectionLine: "Reef / bind",
    likelyPick: "Reef knot to bind; constrictor if it must not walk",
    autoRun: true,
    input: {
      connection: "reef-or-bind",
      mainMaterial: "polyester",
      secondaryMaterial: "polyester",
      diameterRelation: "similar",
      retieFrequency: "occasional",
      proficiency: "beginner",
    },
  },
  {
    id: "hmpe-block-stopper",
    title: "HMPE stopper at a block",
    blurb:
      "Dyneema through a block. A figure-8 walks in this fibre. This is a stopper, not a join.",
    tag: "Working · HMPE",
    connectionLine: "Stopper",
    likelyPick: "EStar stopper",
    autoRun: true,
    input: {
      connection: "stopper",
      mainMaterial: "dyneema",
      retieFrequency: "rare",
      proficiency: "advanced",
    },
  },
  {
    id: "fender-rail",
    title: "Fenders on a rail · slide to adjust",
    blurb:
      "Hang fenders you will still move. A clove hitch is the job. A clove left overnight on a piling is not.",
    tag: "Dock · fenders",
    connectionLine: "Rope → rail",
    likelyPick: "Clove hitch — fast on, fast off, watched",
    autoRun: true,
    input: {
      connection: "rope-to-bollard",
      mainMaterial: "polyester",
      retieFrequency: "frequent",
      proficiency: "beginner",
    },
  },
  {
    id: "trailer-strap",
    title: "Strap the boat for the drive home",
    blurb:
      "Put a line under working tension and lock it. A hitch you will still slide is the wrong job.",
    tag: "Working · lash",
    connectionLine: "Tension / lash",
    likelyPick: "Trucker's hitch — purchase, then two half hitches",
    autoRun: true,
    input: {
      connection: "tension-line",
      mainMaterial: "polyester",
      retieFrequency: "occasional",
      proficiency: "intermediate",
    },
  },
];
