/**
 * Boating Decide starters — domain-local only.
 * Must not be merged into FIELD_SCENARIOS (fishing goldens stay fishing).
 */
import type { FieldScenario } from "@/data/scenarios";

export const BOATING_SCENARIOS: FieldScenario[] = [
  {
    id: "dock-cleat-surge",
    title: "Dock line · horn cleat · surge",
    blurb: "Make fast to a horn cleat so you can still cast off under load. A jammed lock is the hazard.",
    tag: "Dock · release",
    connectionLine: "Rope → cleat",
    likelyPick: "Cleat hitch when the first turn is on the far horn",
    autoRun: true,
    input: {
      connection: "rope-to-cleat",
      mainMaterial: "polyester",
      retieFrequency: "frequent",
      proficiency: "beginner",
    },
  },
  {
    id: "piling-overnight",
    title: "Piling overnight · cyclic tide",
    blurb: "Make fast to a piling you will leave. A clove hitch walks. The turn must take the load.",
    tag: "Mooring · tide",
    connectionLine: "Rope → bollard / piling",
    likelyPick: "Round turn and two half hitches over a clove",
    autoRun: true,
    input: {
      connection: "rope-to-bollard",
      mainMaterial: "nylon",
      retieFrequency: "rare",
      proficiency: "beginner",
    },
  },
  {
    id: "anchor-ring-soak",
    title: "Anchor ring · standing soak",
    blurb: "Rope to a ring that will stay wet. A hitch that works loose after a soak is the fail.",
    tag: "Anchorage",
    connectionLine: "Rope → ring",
    likelyPick: "Anchor bend; seize a standing job",
    autoRun: true,
    input: {
      connection: "rope-to-ring",
      mainMaterial: "nylon",
      retieFrequency: "rare",
      proficiency: "intermediate",
    },
  },
  {
    id: "eye-over-post",
    title: "Finished eye dropped over a post",
    blurb: "A loop you already have, dropped over a piling. Both legs must share the load.",
    tag: "Loops",
    connectionLine: "Loop over a post",
    likelyPick: "Cow hitch when both legs load; bowline if you still need to tie the eye",
    autoRun: true,
    input: {
      connection: "loop-over-post",
      mainMaterial: "polyester",
      retieFrequency: "occasional",
      proficiency: "beginner",
    },
  },
  {
    id: "join-two-docklines",
    title: "Join two dock lines",
    blurb: "Similar-diameter ropes. A sheet bend is fast; a Zeppelin still unties after load.",
    tag: "Join",
    connectionLine: "Rope → rope",
    likelyPick: "Zeppelin when you must untie; sheet bend when speed wins",
    autoRun: true,
    input: {
      connection: "rope-to-rope",
      mainMaterial: "polyester",
      secondaryMaterial: "polyester",
      diameterRelation: "similar",
      retieFrequency: "occasional",
      proficiency: "intermediate",
    },
  },
  {
    id: "unequal-heaving",
    title: "Heaving line onto a hawser",
    blurb: "Thinner line to a thicker one. Bight in the thick rope. One turn is not enough.",
    tag: "Mismatch",
    connectionLine: "Unequal join",
    likelyPick: "Double sheet bend",
    autoRun: true,
    input: {
      connection: "unequal-rope-join",
      mainMaterial: "polypropylene",
      secondaryMaterial: "polyester",
      diameterRelation: "main-much-thinner",
      proficiency: "beginner",
    },
  },
  {
    id: "snubber-chain",
    title: "Snubber onto chain",
    blurb: "Transfer load off the windlass. A rolling hitch is the first try; an icicle if it walks.",
    tag: "Anchorage · snubber",
    connectionLine: "Load transfer",
    likelyPick: "Rolling hitch first; icicle on a slick standing part",
    autoRun: true,
    input: {
      connection: "load-transfer",
      mainMaterial: "nylon",
      retieFrequency: "occasional",
      proficiency: "intermediate",
    },
  },
  {
    id: "midline-chafe",
    title: "Mid-line loop to isolate chafe",
    blurb: "A damaged section in the middle of a working line. An end-loop is the wrong job.",
    tag: "Working · mid-line",
    connectionLine: "Mid-line loop",
    likelyPick: "Alpine butterfly",
    autoRun: true,
    input: {
      connection: "mid-line-loop",
      mainMaterial: "polyester",
      retieFrequency: "rare",
      proficiency: "intermediate",
    },
  },
];
