/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'
import { Route as DiagramKnotIdRouteImport } from './routes/diagram.$knotId'
import { Route as TieKnotIdRouteImport } from './routes/tie.$knotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRoute,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApplicationsRoute,
} as any)
const DiagramKnotIdRoute = DiagramKnotIdRouteImport.update({
  id: '/diagram/$knotId',
  path: '/diagram/$knotId',
  getParentRoute: () => rootRouteImport,
} as any)
const TieKnotIdRoute = TieKnotIdRouteImport.update({
  id: '/tie/$knotId',
  path: '/tie/$knotId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/compare': typeof CompareRoute
  '/diagnose': typeof DiagnoseRoute
  '/library': typeof LibraryRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/diagram/$knotId': typeof DiagramKnotIdRoute
  '/tie/$knotId': typeof TieKnotIdRoute
  '/applications/': typeof ApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/diagnose': typeof DiagnoseRoute
  '/library': typeof LibraryRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/diagram/$knotId': typeof DiagramKnotIdRoute
  '/tie/$knotId': typeof TieKnotIdRoute
  '/applications': typeof ApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/applications': typeof ApplicationsRouteWithChildren
  '/compare': typeof CompareRoute
  '/diagnose': typeof DiagnoseRoute
  '/library': typeof LibraryRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/diagram/$knotId': typeof DiagramKnotIdRoute
  '/tie/$knotId': typeof TieKnotIdRoute
  '/applications/': typeof ApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/applications'
    | '/compare'
    | '/diagnose'
    | '/library'
    | '/applications/$id'
    | '/diagram/$knotId'
    | '/tie/$knotId'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compare'
    | '/diagnose'
    | '/library'
    | '/applications/$id'
    | '/diagram/$knotId'
    | '/tie/$knotId'
    | '/applications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/applications'
    | '/compare'
    | '/diagnose'
    | '/library'
    | '/applications/$id'
    | '/diagram/$knotId'
    | '/tie/$knotId'
    | '/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationsRoute: typeof ApplicationsRouteWithChildren
  CompareRoute: typeof CompareRoute
  DiagnoseRoute: typeof DiagnoseRoute
  LibraryRoute: typeof LibraryRoute
  DiagramKnotIdRoute: typeof DiagramKnotIdRoute
  TieKnotIdRoute: typeof TieKnotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof ApplicationsRoute
    }
    '/diagram/$knotId': {
      id: '/diagram/$knotId'
      path: '/diagram/$knotId'
      fullPath: '/diagram/$knotId'
      preLoaderRoute: typeof DiagramKnotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tie/$knotId': {
      id: '/tie/$knotId'
      path: '/tie/$knotId'
      fullPath: '/tie/$knotId'
      preLoaderRoute: typeof TieKnotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplicationsRouteChildren {
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteChildren: ApplicationsRouteChildren = {
  ApplicationsIdRoute: ApplicationsIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteWithChildren = ApplicationsRoute._addFileChildren(
  ApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationsRoute: ApplicationsRouteWithChildren,
  CompareRoute: CompareRoute,
  DiagnoseRoute: DiagnoseRoute,
  LibraryRoute: LibraryRoute,
  DiagramKnotIdRoute: DiagramKnotIdRoute,
  TieKnotIdRoute: TieKnotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
